spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

server:
  port: 8080
  
 
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'